### PR TITLE
Fix parallel tests

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Want to debug travis output and fix it eventually

### CODE REVIEW

**Comment by quux00** [comment]
Hi Ernestas,

I don't understand the value of this change.  If `Ok(err)` fails, the error is already printed out on this line:

    		fmt.Printf(okFmt, filepath.Base(file), line, err.Error())

But since it's easy to change back later, I'll just merge this in for now.

**Comment by ernestas-poskus** [comment]
Hey, this was still in progress :dizzy_face:

**Comment by quux00** [comment]
OK. I check these in the evenings (US Eastern time).  If you aren't ready for it to be merged put a note or label on it.  Do you want me to revert it?

**Comment by ernestas-poskus** [comment]
> If you aren't ready for it to be merged put a note

:ok_hand:, sorry, no it is not necessary

**Pull request merged**
